# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [ ]:
import numpy as np

In [ ]:
#Creating a sample array
arr_example = np.arange(0,11)

In [ ]:
#Show the array
arr_example

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr_example[8]

8

In [ ]:
#Get values in a range
arr_example[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr_example[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr_example[0:5]=100

#Show
arr_example

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing technique
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:

arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

# Great Job!
